name = "softball-adn-worker"
main = "src/index.ts"
compatibility_date = "2024-06-20"

[vars]
SUPABASE_URL = "https://xgppzyequbzpvaqxhnhc.supabase.co"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "softball-adn"
