/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as StandingsIndexRouteImport } from './routes/standings/index'
import { Route as ScheduleIndexRouteImport } from './routes/schedule/index'
import { Route as PlayersIndexRouteImport } from './routes/players/index'
import { Route as LeadersIndexRouteImport } from './routes/leaders/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'
import { Route as ScheduleGameIdRouteImport } from './routes/schedule/$gameId'
import { Route as PlayersPlayerIdRouteImport } from './routes/players/$playerId'
import { Route as AdminVenuesIndexRouteImport } from './routes/admin/venues/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTeamsIndexRouteImport } from './routes/admin/teams/index'
import { Route as AdminStandingsIndexRouteImport } from './routes/admin/standings/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminSeasonsIndexRouteImport } from './routes/admin/seasons/index'
import { Route as AdminScheduleIndexRouteImport } from './routes/admin/schedule/index'
import { Route as AdminRostersIndexRouteImport } from './routes/admin/rosters/index'
import { Route as AdminPositionsIndexRouteImport } from './routes/admin/positions/index'
import { Route as AdminPlayersIndexRouteImport } from './routes/admin/players/index'
import { Route as AdminGameReportsIndexRouteImport } from './routes/admin/game-reports/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminChurchesIndexRouteImport } from './routes/admin/churches/index'
import { Route as AdminAuditLogIndexRouteImport } from './routes/admin/audit-log/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsIndexRoute = StandingsIndexRouteImport.update({
  id: '/standings/',
  path: '/standings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadersIndexRoute = LeadersIndexRouteImport.update({
  id: '/leaders/',
  path: '/leaders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleGameIdRoute = ScheduleGameIdRouteImport.update({
  id: '/schedule/$gameId',
  path: '/schedule/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVenuesIndexRoute = AdminVenuesIndexRouteImport.update({
  id: '/admin/venues/',
  path: '/admin/venues/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsIndexRoute = AdminTeamsIndexRouteImport.update({
  id: '/admin/teams/',
  path: '/admin/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStandingsIndexRoute = AdminStandingsIndexRouteImport.update({
  id: '/admin/standings/',
  path: '/admin/standings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/admin/settings/',
  path: '/admin/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeasonsIndexRoute = AdminSeasonsIndexRouteImport.update({
  id: '/admin/seasons/',
  path: '/admin/seasons/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScheduleIndexRoute = AdminScheduleIndexRouteImport.update({
  id: '/admin/schedule/',
  path: '/admin/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRostersIndexRoute = AdminRostersIndexRouteImport.update({
  id: '/admin/rosters/',
  path: '/admin/rosters/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPositionsIndexRoute = AdminPositionsIndexRouteImport.update({
  id: '/admin/positions/',
  path: '/admin/positions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlayersIndexRoute = AdminPlayersIndexRouteImport.update({
  id: '/admin/players/',
  path: '/admin/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGameReportsIndexRoute = AdminGameReportsIndexRouteImport.update({
  id: '/admin/game-reports/',
  path: '/admin/game-reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/admin/dashboard/',
  path: '/admin/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChurchesIndexRoute = AdminChurchesIndexRouteImport.update({
  id: '/admin/churches/',
  path: '/admin/churches/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogIndexRoute = AdminAuditLogIndexRouteImport.update({
  id: '/admin/audit-log/',
  path: '/admin/audit-log/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/schedule/$gameId': typeof ScheduleGameIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/leaders/': typeof LeadersIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/standings/': typeof StandingsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/admin/audit-log/': typeof AdminAuditLogIndexRoute
  '/admin/churches/': typeof AdminChurchesIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/game-reports/': typeof AdminGameReportsIndexRoute
  '/admin/players/': typeof AdminPlayersIndexRoute
  '/admin/positions/': typeof AdminPositionsIndexRoute
  '/admin/rosters/': typeof AdminRostersIndexRoute
  '/admin/schedule/': typeof AdminScheduleIndexRoute
  '/admin/seasons/': typeof AdminSeasonsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/standings/': typeof AdminStandingsIndexRoute
  '/admin/teams/': typeof AdminTeamsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/venues/': typeof AdminVenuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/schedule/$gameId': typeof ScheduleGameIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/leaders': typeof LeadersIndexRoute
  '/players': typeof PlayersIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/standings': typeof StandingsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/admin/audit-log': typeof AdminAuditLogIndexRoute
  '/admin/churches': typeof AdminChurchesIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/game-reports': typeof AdminGameReportsIndexRoute
  '/admin/players': typeof AdminPlayersIndexRoute
  '/admin/positions': typeof AdminPositionsIndexRoute
  '/admin/rosters': typeof AdminRostersIndexRoute
  '/admin/schedule': typeof AdminScheduleIndexRoute
  '/admin/seasons': typeof AdminSeasonsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/standings': typeof AdminStandingsIndexRoute
  '/admin/teams': typeof AdminTeamsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/venues': typeof AdminVenuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/schedule/$gameId': typeof ScheduleGameIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/leaders/': typeof LeadersIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/standings/': typeof StandingsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/admin/audit-log/': typeof AdminAuditLogIndexRoute
  '/admin/churches/': typeof AdminChurchesIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/game-reports/': typeof AdminGameReportsIndexRoute
  '/admin/players/': typeof AdminPlayersIndexRoute
  '/admin/positions/': typeof AdminPositionsIndexRoute
  '/admin/rosters/': typeof AdminRostersIndexRoute
  '/admin/schedule/': typeof AdminScheduleIndexRoute
  '/admin/seasons/': typeof AdminSeasonsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/standings/': typeof AdminStandingsIndexRoute
  '/admin/teams/': typeof AdminTeamsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/venues/': typeof AdminVenuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/players/$playerId'
    | '/schedule/$gameId'
    | '/teams/$teamId'
    | '/about/'
    | '/admin/'
    | '/leaders/'
    | '/players/'
    | '/schedule/'
    | '/standings/'
    | '/teams/'
    | '/admin/audit-log/'
    | '/admin/churches/'
    | '/admin/dashboard/'
    | '/admin/game-reports/'
    | '/admin/players/'
    | '/admin/positions/'
    | '/admin/rosters/'
    | '/admin/schedule/'
    | '/admin/seasons/'
    | '/admin/settings/'
    | '/admin/standings/'
    | '/admin/teams/'
    | '/admin/users/'
    | '/admin/venues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/players/$playerId'
    | '/schedule/$gameId'
    | '/teams/$teamId'
    | '/about'
    | '/admin'
    | '/leaders'
    | '/players'
    | '/schedule'
    | '/standings'
    | '/teams'
    | '/admin/audit-log'
    | '/admin/churches'
    | '/admin/dashboard'
    | '/admin/game-reports'
    | '/admin/players'
    | '/admin/positions'
    | '/admin/rosters'
    | '/admin/schedule'
    | '/admin/seasons'
    | '/admin/settings'
    | '/admin/standings'
    | '/admin/teams'
    | '/admin/users'
    | '/admin/venues'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/players/$playerId'
    | '/schedule/$gameId'
    | '/teams/$teamId'
    | '/about/'
    | '/admin/'
    | '/leaders/'
    | '/players/'
    | '/schedule/'
    | '/standings/'
    | '/teams/'
    | '/admin/audit-log/'
    | '/admin/churches/'
    | '/admin/dashboard/'
    | '/admin/game-reports/'
    | '/admin/players/'
    | '/admin/positions/'
    | '/admin/rosters/'
    | '/admin/schedule/'
    | '/admin/seasons/'
    | '/admin/settings/'
    | '/admin/standings/'
    | '/admin/teams/'
    | '/admin/users/'
    | '/admin/venues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  ScheduleGameIdRoute: typeof ScheduleGameIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LeadersIndexRoute: typeof LeadersIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  StandingsIndexRoute: typeof StandingsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  AdminAuditLogIndexRoute: typeof AdminAuditLogIndexRoute
  AdminChurchesIndexRoute: typeof AdminChurchesIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminGameReportsIndexRoute: typeof AdminGameReportsIndexRoute
  AdminPlayersIndexRoute: typeof AdminPlayersIndexRoute
  AdminPositionsIndexRoute: typeof AdminPositionsIndexRoute
  AdminRostersIndexRoute: typeof AdminRostersIndexRoute
  AdminScheduleIndexRoute: typeof AdminScheduleIndexRoute
  AdminSeasonsIndexRoute: typeof AdminSeasonsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminStandingsIndexRoute: typeof AdminStandingsIndexRoute
  AdminTeamsIndexRoute: typeof AdminTeamsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminVenuesIndexRoute: typeof AdminVenuesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings/': {
      id: '/standings/'
      path: '/standings'
      fullPath: '/standings/'
      preLoaderRoute: typeof StandingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaders/': {
      id: '/leaders/'
      path: '/leaders'
      fullPath: '/leaders/'
      preLoaderRoute: typeof LeadersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/$gameId': {
      id: '/schedule/$gameId'
      path: '/schedule/$gameId'
      fullPath: '/schedule/$gameId'
      preLoaderRoute: typeof ScheduleGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/venues/': {
      id: '/admin/venues/'
      path: '/admin/venues'
      fullPath: '/admin/venues/'
      preLoaderRoute: typeof AdminVenuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams/': {
      id: '/admin/teams/'
      path: '/admin/teams'
      fullPath: '/admin/teams/'
      preLoaderRoute: typeof AdminTeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/standings/': {
      id: '/admin/standings/'
      path: '/admin/standings'
      fullPath: '/admin/standings/'
      preLoaderRoute: typeof AdminStandingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/admin/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seasons/': {
      id: '/admin/seasons/'
      path: '/admin/seasons'
      fullPath: '/admin/seasons/'
      preLoaderRoute: typeof AdminSeasonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schedule/': {
      id: '/admin/schedule/'
      path: '/admin/schedule'
      fullPath: '/admin/schedule/'
      preLoaderRoute: typeof AdminScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rosters/': {
      id: '/admin/rosters/'
      path: '/admin/rosters'
      fullPath: '/admin/rosters/'
      preLoaderRoute: typeof AdminRostersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/positions/': {
      id: '/admin/positions/'
      path: '/admin/positions'
      fullPath: '/admin/positions/'
      preLoaderRoute: typeof AdminPositionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/players/': {
      id: '/admin/players/'
      path: '/admin/players'
      fullPath: '/admin/players/'
      preLoaderRoute: typeof AdminPlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/game-reports/': {
      id: '/admin/game-reports/'
      path: '/admin/game-reports'
      fullPath: '/admin/game-reports/'
      preLoaderRoute: typeof AdminGameReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/churches/': {
      id: '/admin/churches/'
      path: '/admin/churches'
      fullPath: '/admin/churches/'
      preLoaderRoute: typeof AdminChurchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-log/': {
      id: '/admin/audit-log/'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log/'
      preLoaderRoute: typeof AdminAuditLogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  ScheduleGameIdRoute: ScheduleGameIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  AboutIndexRoute: AboutIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  LeadersIndexRoute: LeadersIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  StandingsIndexRoute: StandingsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  AdminAuditLogIndexRoute: AdminAuditLogIndexRoute,
  AdminChurchesIndexRoute: AdminChurchesIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminGameReportsIndexRoute: AdminGameReportsIndexRoute,
  AdminPlayersIndexRoute: AdminPlayersIndexRoute,
  AdminPositionsIndexRoute: AdminPositionsIndexRoute,
  AdminRostersIndexRoute: AdminRostersIndexRoute,
  AdminScheduleIndexRoute: AdminScheduleIndexRoute,
  AdminSeasonsIndexRoute: AdminSeasonsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminStandingsIndexRoute: AdminStandingsIndexRoute,
  AdminTeamsIndexRoute: AdminTeamsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminVenuesIndexRoute: AdminVenuesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
